allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
classpath 'com.google.gms:google-services:4.3.10' // Verifique se a versão está atualizada

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
