// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARTGJEQOoeMH8dyDPJ6dBg6LqzICKdC6Y',
    appId: '1:1094621998423:web:1c2d49459341583cf9e212',
    messagingSenderId: '1094621998423',
    projectId: 'fitbudi-4c6da',
    authDomain: 'fitbudi-4c6da.firebaseapp.com',
    storageBucket: 'fitbudi-4c6da.firebasestorage.app',
    measurementId: 'G-KMZYMH8JKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnIaesu7ioXkA9hSTA0q0M0Lh3Uz44NFE',
    appId: '1:1094621998423:android:b895eca379b5967ef9e212',
    messagingSenderId: '1094621998423',
    projectId: 'fitbudi-4c6da',
    storageBucket: 'fitbudi-4c6da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhylvYxprf9utNqAZDp3Fl5Zi9q06X2sk',
    appId: '1:1094621998423:ios:f9108d4dcc037e02f9e212',
    messagingSenderId: '1094621998423',
    projectId: 'fitbudi-4c6da',
    storageBucket: 'fitbudi-4c6da.firebasestorage.app',
    iosBundleId: 'com.example.fitbudi1',
  );
}
