// android/app/build.gradle

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'  // Plugin Kotlin para o Android
apply plugin: 'com.google.gms.google-services'  // Plugin do Google Services

android {
    namespace = "com.example.fitbudi_1"  // Namespace do aplicativo
    compileSdkVersion 33  // Versão do SDK de compilação

    defaultConfig {
        applicationId "com.example.fitbudi_1"  // ID único do aplicativo
        minSdkVersion 21  // Versão mínima suportada
        targetSdkVersion 33  // Versão do SDK alvo
        versionCode 1  // Número da versão
        versionName "1.0"  // Nome da versão
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug  // Usando a configuração de assinatura de debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8  // Compatibilidade com Java 8
        targetCompatibility JavaVersion.VERSION_1_8  // Compatibilidade com Java 8
    }

    kotlinOptions {
        jvmTarget = "1.8"  // Definindo o alvo do Kotlin
    }
}

dependencies {
    implementation 'com.google.firebase:firebase-analytics:21.2.0'  // Exemplo de dependência do Firebase Analytics
    implementation 'com.google.firebase:firebase-auth:21.1.0'  // Exemplo de dependência do Firebase Auth
    implementation 'com.google.firebase:firebase-firestore:24.4.0'  // Exemplo de dependência do Firestore
}

apply plugin: 'com.google.gms.google-services'  // Aplica o plugin do Google Services
